### ISSUE TITLE
не работает ввод количества отображаемого товара у поставщика и у модератора

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#100]
сделать его не способом ввода числа, а фильтром, чтоб пользователь мог выбрать из предложеных вариантов: 25,50,75,100 товаров на листе
![8](https://cloud.githubusercontent.com/assets/11805589/7857634/a4dd9fa8-053a-11e5-9fe9-7b54fba66033.JPG)

**Comment by ihteandr** [comment]
оставил поле для ввода но изменил работы тепер не надо будет убериать фокус с елемента чтобы увидеть разницу

**Comment by msheremet** [comment]
я не понял тебя.
 что изменилось?
не работает по прежнему.

**Comment by ihteandr** [comment]
работает!! я проверял

**Comment by msheremet** [comment]
у меня в firefox не работает
попробуй и ты в этом браузере...

**Comment by msheremet** [comment]
так и есть
в firefox почему-то не работает ввод цифр.
я проверял в карточке товара вводить белки, углеводы, номер телефона...тоже не работает.

**Comment by ihteandr** [comment]
справил для фаирфокса

**Comment by msheremet** [comment]
ок, заработало.!
