### ISSUE TITLE
подгрузка товара у юзера

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#108]
Сделать автоподгрузку товара при скроле когда до конца загруженного товара остается 2 строки.
(сейчас из-за того, что подгрузка происходит только при прокрутке до конца, юзеру необходимо ждать какое-то время)

**Comment by ihteandr** [comment]
Оно так и работает, сейчас я зделал чтобы делая 70% скрола данные подгружались но ты это не заметиш если зделаш быстрый скролл вниз все равно будеш ждать потомучто для подгрузки новых товаров нужно время

**Comment by msheremet** [comment]
Ok

2015-06-15 20:14 GMT+03:00 Vladimir Ghukasyan notifications@github.com:

**Comment by msheremet** [comment]
просто я смотрю на сколько шустро подгрузка работает на этом сайте, и мне
кажется что у них это происходит на много быстрее
http://www.gotoshop.net.ua/kiev/produkty/
это из-за того, что мы сейчас на слабеньком серваке?

2015-06-16 9:39 GMT+03:00 Максим Шеремет maksymsheremet@gmail.com:

**Comment by ihteandr** [comment]
зделал чтобы было также шусро как и у них, но для меня это слишком шистро
