### ISSUE TITLE
при загрузке товара (2 скрина)

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#117]
после того как я отправил файл на загрузку мне сначала выдало это:

![image](https://cloud.githubusercontent.com/assets/11805589/8885312/0f4965d0-3267-11e5-976d-6002177c005f.png)

а потом это:

![image](https://cloud.githubusercontent.com/assets/11805589/8885318/1915f236-3267-11e5-9ebf-2284e46328bc.png)

**Comment by ihteandr** [comment]
зделал так чтобы выдавало нормальную ошибки если файл загрузился не правельно
