### ISSUE TITLE
Что тут не так с авторизацией поставщика?

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#149]
![1](https://cloud.githubusercontent.com/assets/11805589/9523595/6626cbd6-4ce3-11e5-9288-71f38a45cf03.JPG)

**Comment by ihteandr** [comment]
Пользователь с таким почтовым адрессом уже есть

**Comment by msheremet** [comment]
удалить его можешь?

2015-08-27 18:48 GMT+03:00 Vladimir Ghukasyan notifications@github.com:
