### ISSUE TITLE
не грузится модератор

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#160]
![image](https://cloud.githubusercontent.com/assets/11805589/9657217/b4a40fda-5247-11e5-835f-4fb5371af59b.png)

PS: через 5 минут уже загрузилось,  но разобраться думаю стоит...?

5 минут спустя:
![image](https://cloud.githubusercontent.com/assets/11805589/9657405/717d5778-5249-11e5-9a5f-44c720173338.png)

**Comment by ihteandr** [comment]
незнаю почему так может я делал рестарт
