### ISSUE TITLE
убрать лишний вывод

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#161]
у поставщика и модератора если в поле "единица измерения" пусто, то на главной странице  вылазит в наименовании лишнее значение "ШТ"

![image](https://cloud.githubusercontent.com/assets/11805589/9682339/7fb4ffba-530e-11e5-9d04-b4482dfb7fb3.png)

**Comment by ihteandr** [comment]
это не лишнее это еденица обьема/веса

**Comment by msheremet** [comment]
я понимаю, что это единица измерения, но в карточке товара она не заполнена, по этому должно быть пусто:
![image](https://cloud.githubusercontent.com/assets/11805589/9715507/934173bc-5569-11e5-91e6-7d3056e27e97.png)

**Comment by ihteandr** [comment]
Ошибка была на странице продукта там не отображалась еденица измерения

**Comment by msheremet** [comment]
ок, ясно.
я вижу, ты пока не исправил эту ошибку в продуктах?...

7 сентября 2015 г., 14:29 пользователь Vladimir Ghukasyan <
notifications@github.com> написал:

**Comment by ihteandr** [comment]
Исправил
