### ISSUE TITLE
порядок отображения в закладке "Акции"

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#166]
при нажатии юзером на "Акции" можно ли выводить выгружаемые картинки в том порядке, в котором я их загружал на сервер? а то получается какой-то рандомный порядок (я брал листовки, сканировал их по порядку и в том же порядке их загружал...так как листовки тематические, то лучше чтоб порядок выгрузки сохранялся)

также убрать функцию календаря "Дата с" и "Дата по"

и желательно сохранять исходные соотношения сторон картинок (так как одни имеют горизонтальную ориентацию, а другие вертикальную)

![image](https://cloud.githubusercontent.com/assets/11805589/9683127/d7b1982a-5315-11e5-90ba-26209293917d.png)

и в акциях, которые есчё не начались вместо "Осталось" писать "Начало через"

![image](https://cloud.githubusercontent.com/assets/11805589/9683101/89ae00aa-5315-11e5-8dd3-3638684eb853.png)

**Comment by ihteandr** [comment]
должно работать по крайне мере для новосозданных акций
