### ISSUE TITLE
поиск названия товара

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#169]
при поиске товара "лавровЫй лист" не выдает результат, а при "лавровИй лист" находит.
сделай, чтоб буквы Ы,И,і были равными в поиске.

**Comment by ihteandr** [comment]
Привет, зделал.Можеш попробывать набрать pivo и получиш результат.Прешли мне все быквы в которых по твоиму могут ошибится люди, я их добавлю

**Comment by msheremet** [comment]
2015-09-13 7:08 GMT+03:00 Vladimir Ghukasyan notifications@github.com:
