### ISSUE TITLE
избранное в карточке товара

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#172]
звездочка "избранное" появляется только после перезагрузки страницы (F5)
![image](https://cloud.githubusercontent.com/assets/11805589/9729093/7560e6c8-5615-11e5-81e0-a1d73930d516.png)

**Comment by msheremet** [comment]
функция вообще перестала работать:
- в карточке товара нет возможности нажать на нее
- в основном рабочем экране (там где все товары вместе) при нажатии на добавление в избранное просто грузится, но не добавляет

**Comment by ihteandr** [comment]
Я изменил так чтобы изпронное привязывалось к ЗКПО а не к юзеру

**Comment by msheremet** [comment]
супер

24 сентября 2015 г., 15:04 пользователь Vladimir Ghukasyan <
notifications@github.com> написал:
