### ISSUE TITLE
небольшой баг с ценами в карточке товара у Поставика

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#181]
если сначала нажать/кликнуть на какую-то цену, а потом кликнуть на поле для ввода новой цены, то все цены куда-то исчезают, но после рефреша появляются:

![image](https://cloud.githubusercontent.com/assets/11805589/10074263/806607d2-62d7-11e5-85f1-0c723dd7225b.png)

**Comment by ihteandr** [comment]
ne smog povtority, ya tam koechto pomenyal mojet i eto pofiksil

**Comment by msheremet** [comment]
всё Ок

2015-09-24 20:06 GMT+03:00 Vladimir Ghukasyan notifications@github.com:
