### ISSUE TITLE
загрузка нового товара (скрол)

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#189]
если прокручиваю в развернутом на 100 рабочем окне, то слово ЗАГРУЗКА не появляется (картинка 1).
а если хром развернут не полностью, то ЗАГРУЗКА есть и скрол подгружает новый товар (картинка 2).
1: 
![image](https://cloud.githubusercontent.com/assets/11805589/10392652/a3f49f72-6e91-11e5-8d6a-a28087e2e707.png)

2:
![image](https://cloud.githubusercontent.com/assets/11805589/10392684/0a698e48-6e92-11e5-8abe-a9b4b5baf775.png)

**Comment by ihteandr** [comment]
Не смог повторить, но я зделал кое какие изменения иза которых это могло возникнуть

**Comment by msheremet** [comment]
помогло

11 октября 2015 г., 15:36 пользователь Vladimir Ghukasyan <
notifications@github.com> написал:
