### ISSUE TITLE
скрыть информацию

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#202]
скрой пока из политики конфиденциальности эту информацию:
вместо этого написать просто:       omprice.com@gmail.com
когда будут готовы уставные документы на компанию, тогда пропишем наш юридический адрес правильно.

![image](https://cloud.githubusercontent.com/assets/11805589/11058133/41e677c6-8799-11e5-9379-c0e88071ccc3.png)

**Comment by msheremet** [comment]
ни чего не поменялось:

![image](https://cloud.githubusercontent.com/assets/11805589/11187440/13f98cc2-8c8f-11e5-97a1-1913c5ec8739.png)

**Comment by ihteandr** [comment]
удалил
