### ISSUE TITLE
фильтр по количеству товара (поставщик)

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#214]
если я ставлю на отображение вместо 25шт например 50, то после подгрузки количество не меняется, остается 25,
но если перейти на следующий лист товаров, то там уже будет 50шт, и если вернуться на первый лист, то и там уже будет 50.

также сделай пожалуйста, чтоб после рефреша не слетал фильтр.

**Comment by ihteandr** [comment]
первую часть не понял, не чего похожево не заметил, зделал сохронение для постовщика, на модераторе это уже было, зделал ограничение на количесто вводимово лимита получаемых товаров 200
