### ISSUE TITLE
проработанные парсером файлы

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#218]
а можно чтоб ексели не заменялись на последний по выгрузке, а в колонку шли подряд по убыванию даты?

![1](https://cloud.githubusercontent.com/assets/11805589/11623014/9007407c-9cd2-11e5-8143-1ced4b278de1.jpg)

**Comment by ihteandr** [comment]
зделал, сейчас будут сохранятся полседние 10 файлов, и 
я добавил возможность отправлять сразу несколько файлов, проверь это пожалуйста
