### ISSUE TITLE
вопрос

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#221]
а почему тут не добавлеются нужное количество  нулей?
мы ведь обсуждали добавление недостающих "0" к штрихкоду чтоб в сумме было 14 знаков...?
вот для примера на новус.заказ.юа: штрихкод "42139485" не находит, а "00000042139485" находит

![image](https://cloud.githubusercontent.com/assets/11805589/11688910/f5cb065c-9e97-11e5-97ec-5a7bc576cb34.png)

**Comment by ihteandr** [comment]
зделал
