### ISSUE TITLE
поставщик - ввод цены через запятую

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#223]
сделать ввод как через точку, так и через запятую
![image](https://cloud.githubusercontent.com/assets/11805589/11769163/44122350-a1e9-11e5-850f-ea28c3ed6b1f.png)

**Comment by ihteandr** [comment]
там так и есть, вводиш запетую она становится точкой

**Comment by msheremet** [comment]
если корректировать цену по магазину, которая уже есть, то запятая
заменяется на точку, но если вводить новую цену по магазину, цены которого
по товару нет, то запятая не автозаменяется, и получается, что при вводе
числа например 35,05 получаем цену 35,00 в итоге

![image](https://cloud.githubusercontent.com/assets/11805589/12720641/70018888-c904-11e5-9204-94b872bb854c.png)

2016-01-26 6:13 GMT+02:00 Vladimir Ghukasyan notifications@github.com:
