### ISSUE TITLE
удаление EAN поставщиком

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#42]
![image](https://cloud.githubusercontent.com/assets/11805589/7166869/682c7b3a-e3b9-11e4-9b40-daba8da4e143.png)
![image](https://cloud.githubusercontent.com/assets/11805589/7166874/6d027a92-e3b9-11e4-8aa7-60e5904fde32.png)

**Comment by ihteandr** [comment]
Я удалил функцию удаления уже сиществующих еан для поставщиков

**Comment by msheremet** [comment]
зачем?
а если существующий еан был по ошибке внесен в карточку товара? как поставщик удалит его из карточки?
