### ISSUE TITLE
ошибка

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#44]
![1](https://cloud.githubusercontent.com/assets/11805589/7176661/f822c73e-e428-11e4-8b49-c59a8da096fd.JPG)

**Comment by ihteandr** [comment]
Не смог воспроизвести проблему

**Comment by msheremet** [comment]
сначала переходи в 
БАКАЛЕЯ - ГАРНИРЫ - МАКАРОННЫЕ ИЗДЕЛИЯ
а потом переходи например в АЛКОГОЛЬНЫЕ НАПИТКИ - ТЕКИЛА

такое при переходах от рынок-категория-семья    в   что-то не так глубоко: в другой  рынок-категория или просто рынок
