### ISSUE TITLE
сохранение изображений поставщиком

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#47]
если поставщик добавляет фото товара и нажмет сохранить, но не нажимает "вернуться", а остается в карточке товара,
то модератор у себя видит заявку на изменение заходит в нее, видит добавленную фотку, нажимает на "подтвердить". в результате фото не добавляется.

для того чтоб добавилось фото сейчас поставщику обязательно после добавления картинки надо вернуться в главное меню.

можно сделать, чтоб сохраняло в любом случае?

**Comment by ihteandr** [comment]
Если ты имееш введу что последобавления кортинки и сохранение постовщик видет что кортинку и она в краснам цвете и ты хочеш зделать так чтобы она стало нормальной то 
впринцепе это возможно но сейчас нам этого не надо это дабавит такие сложности с каторыми я бы не хотел сталкиватся на нынешнем этапе поэкта, это можно будет зделать в следующей версии.
Я если ты имееш введу что он ее просто не видет то я не смог повторить эту сетуацию
