### ISSUE TITLE
вывод товара

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#50]
сделать так, чтоб можно было выбирать не только тот товар, который залит по ценам в этих магазинах, но и чтоб можно было видеть весь товар, который у нас есть в базе.

![4](https://cloud.githubusercontent.com/assets/11805589/7225877/987b18c4-e74b-11e4-9473-38a08517250c.JPG)

**Comment by ihteandr** [comment]
Не смог поставить русский, были какието проблемы с кодировокой которые не смог разрешить
