### ISSUE TITLE
no image photo

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#58]
если нет фото, то применять эти фотографии:
(сдесь расположены от превого до 16 рынка по возростанию)

![01](https://cloud.githubusercontent.com/assets/11805589/7321262/dd1e2f28-eaa9-11e4-96ca-0b059be87fd8.png)
![02](https://cloud.githubusercontent.com/assets/11805589/7321265/dd20c8d2-eaa9-11e4-9913-b852bc3b6cde.png)
![03](https://cloud.githubusercontent.com/assets/11805589/7321261/dd1d3c6c-eaa9-11e4-8af5-fd1d068def7b.jpg)
![04](https://cloud.githubusercontent.com/assets/11805589/7321264/dd20d7f0-eaa9-11e4-9757-e3a5f0be6f1c.png)
![05](https://cloud.githubusercontent.com/assets/11805589/7321263/dd1e76d6-eaa9-11e4-80d9-84fed43cea4c.png)
![06](https://cloud.githubusercontent.com/assets/11805589/7321260/dd1cc048-eaa9-11e4-9b39-f6846261b61b.png)
![07](https://cloud.githubusercontent.com/assets/11805589/7321266/dd339818-eaa9-11e4-8a36-2e505f892f89.png)
![08](https://cloud.githubusercontent.com/assets/11805589/7321268/dd3512e2-eaa9-11e4-826f-6f382c7e9037.png)
![09](https://cloud.githubusercontent.com/assets/11805589/7321267/dd344844-eaa9-11e4-868f-6e201e19c157.png)
![10](https://cloud.githubusercontent.com/assets/11805589/7321269/dd366a7a-eaa9-11e4-9963-b9dcd834ec75.png)
![11](https://cloud.githubusercontent.com/assets/11805589/7321271/dd3968f6-eaa9-11e4-92e0-7253df2c3b6d.png)
![12](https://cloud.githubusercontent.com/assets/11805589/7321270/dd392684-eaa9-11e4-8741-97cdbefc8221.png)
![13](https://cloud.githubusercontent.com/assets/11805589/7321272/dd4acf2e-eaa9-11e4-9f4b-0251c0204aef.png)
![14](https://cloud.githubusercontent.com/assets/11805589/7321274/dd4dc058-eaa9-11e4-9fd1-ff068bfa6d91.png)
![15](https://cloud.githubusercontent.com/assets/11805589/7321273/dd4ca34e-eaa9-11e4-8966-bcbef1e4a90d.png)
![16](https://cloud.githubusercontent.com/assets/11805589/7321275/dd506e7a-eaa9-11e4-9525-9a4a161e1e93.png)

**Comment by ihteandr** [comment]
измени картинку для 3-го рынка на .png. (/public/images/products/)

**Comment by msheremet** [comment]
![03](https://cloud.githubusercontent.com/assets/11805589/7339410/3511cef6-ec76-11e4-84ce-d64db2ab8b8b.png)

**Comment by msheremet** [comment]
2015-04-26 0:31 GMT+03:00 Vladimir Ghukasyan notifications@github.com:
