### ISSUE TITLE
зависает сортировка отображения

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#62]
1. перехожу к большему радиусу поиска магазинов 
2. переключаюсь с "all products" на "products in shops"
3. товар без цен не исчезает
   ![image](https://cloud.githubusercontent.com/assets/11805589/7332599/6a78f4d4-eb4f-11e4-8431-1c87f8f574fa.png)

**Comment by ihteandr** [comment]
я исправил проблем с запросом с большим количеством магазинов, после этого не смог повторить
