### ISSUE TITLE
у модератора не переключает на главной странице между фотографиями

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#64]
![image](https://cloud.githubusercontent.com/assets/11805589/7339392/a3680bc8-ec75-11e4-866f-ce0a724f3af6.png)

**Comment by ihteandr** [comment]
Не смог воспроизвести, но заметил чтото странное когда открываю бакалею продукты какето другие, проверь данные приходят правельные или нет

**Comment by msheremet** [comment]
я в интерфейсе модератора так и не могу переключаться между фотографимяи на основной странице.
в бакалее ни чего не заметил..., а ты что там странного заметил?
