### ISSUE TITLE
дублирование цены

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#70]
для примера взял бакалею.
во многих товарах с залитыми ценами есть случаи, когда обе цены принадлежат магазину "Фуршет-Спортивная пл.,1"
![1](https://cloud.githubusercontent.com/assets/11805589/7343606/f5008ed2-eccb-11e4-9fed-b43d4b8f2823.JPG)

**Comment by ihteandr** [comment]
ошибку исправил, но уже существующие остались, они исчезнут после следующей загрузке цен

**Comment by msheremet** [comment]
ок, супер

2015-04-27 19:35 GMT+03:00 Vladimir Ghukasyan notifications@github.com:
