### ISSUE TITLE
отображение на главной странице (у всех пользователей)

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#71]
![1](https://cloud.githubusercontent.com/assets/11805589/7343897/8f13b4d8-eccf-11e4-9af6-a1ab26334006.JPG)

у модератора и поставщика название опустить так же как у юзера вниз карточки товара
![2](https://cloud.githubusercontent.com/assets/11805589/7343973/4e170aec-ecd0-11e4-929e-f752f3f462f5.JPG)

**Comment by ihteandr** [comment]
я не могу зделать отдельное формотироване для отдельной картинки, лучще тебе изменить картинки
