### ISSUE TITLE
выбор основного магазина лучше сделать таким образом,....это будет более наглядно для юзеров

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#72]
![3](https://cloud.githubusercontent.com/assets/11805589/7344647/229b06ce-ecd6-11e4-9f76-666cf3f5d52c.JPG)

**Comment by ihteandr** [comment]
зделал не много по другому просто кликаеш на магазин

**Comment by msheremet** [comment]
ок, так даже лучше
