### ISSUE TITLE
Cannot GET /moderator/ 

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#73]
почему такое случается?

![4](https://cloud.githubusercontent.com/assets/11805589/7344700/a27a1d58-ecd6-11e4-8a05-3502d79ad47c.JPG)

**Comment by ihteandr** [comment]
По разным пречинам в этот раз из того что я в этот момент обновлял папку с кодом, в прошлый иза того что я внес измания которы не поддерживал сервер

**Comment by msheremet** [comment]
ясно

27 апреля 2015 г., 13:22 пользователь Vladimir Ghukasyan <
notifications@github.com> написал:
