### ISSUE TITLE
если поставщик зарегестрирован, то добавить такой функционал:

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#78]
ПЕРЕД РЕАЛИЗАЦИЕЙ ЭТОЙ ФУНКЦИИ ПОСМОТРИ ТИКЕТ №79

P.S.: одиин и тот же товар может быть добавлен к любому количеству  пользователей

![6](https://cloud.githubusercontent.com/assets/11805589/7347717/effad91a-ecf3-11e4-9556-bf099758e58f.JPG)
![5](https://cloud.githubusercontent.com/assets/11805589/7347718/effb1bbe-ecf3-11e4-871d-cfc0f886f2e2.JPG)

**Comment by ihteandr** [comment]
зделал немного по другому, но тоже нормально, не видел второй слайд
