### ISSUE TITLE
добавить в интерфейс поставщика 2 шаблона для скачивания

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#82]
ексель-файлы отправил на почту

![1](https://cloud.githubusercontent.com/assets/11805589/7354733/065dc7bc-ed26-11e4-84ae-2c62615eea01.jpg)

**Comment by ihteandr** [comment]
скинь суда шаблоны

**Comment by msheremet** [comment]
2015-06-01 14:37 GMT+03:00 Vladimir Ghukasyan notifications@github.com:

**Comment by msheremet** [comment]
получил?
