### ISSUE TITLE
регистрация юзеров

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#84]
основным и наиболее легким способом регистрации сделать Регистрацию пользователей через аккаунты социальных сетей (vk.ru, ok.ru, facebook, google+) - расположено по популярности использования в Украине.

это поможет нам в использовании данных из их аккаунтов в демографических анализах покупок. И как вывод это повысит ценность наших отчетов.

**Comment by ihteandr** [comment]
зделал регестарцию через вконтакте и файсбук думаю этого хватит

**Comment by ihteandr** [comment]
в дольнейшем можено добавить и другие типа твитар, нам думаю в основном будут мужны сети которые связаны с социальной жизнью и не как не типа linkedin

**Comment by msheremet** [comment]
твитер не так популярен в Украине
так что фейсбук и вконтакте вполне хватит пока.
