### ISSUE TITLE
детализация корзины по магазинам

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#89]
1. выбираем любой магазин из списка сравнения общих сумм
   ![7](https://cloud.githubusercontent.com/assets/11805589/7367097/b571df5c-eda5-11e4-8bbc-a5accd3c27b5.JPG)
2. получаем развернутую картину по наличию товара в этом магазине
   (в этом иже окне юзер может добавлять или отнимать количество товара в корзину)
   ![8](https://cloud.githubusercontent.com/assets/11805589/7367179/3b65ce66-eda6-11e4-87ba-4c0b3cf13656.JPG)
   позже мы пропишем сдесь алгоритм замены товара на тот, который есть в магазине, либо замену товара на более дешевый аналог.

**Comment by ihteandr** [comment]
нам это пока не нужно
