### ISSUE TITLE
выборка по торговой марке

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#93]
![2](https://cloud.githubusercontent.com/assets/11805589/7409097/33684efa-ef2c-11e4-8dea-84cb00aa8a87.JPG)

**Comment by ihteandr** [comment]
Зделал, но прешлось делать и внутрение измениеня в системе для этого так что возможно чтото поломалось завтро праверю, но измения вступят в силу только после следующей загрузки продуктов или изменения конкретног продукта
