### ISSUE TITLE
поиск у поставщика (у модератора сделать так же, только без звездочек-добавления в избранное) 2 скрина)

### ISSUE THREAD

**Issue by msheremet** [ihteandr/Public#99]
это упростит поиск товара по категориям, для поставщиков будет проще добавлять товар в избранное и результат поиска будет намного нагляднее (так как будет с фотографиями)
![6](https://cloud.githubusercontent.com/assets/11805589/7857502/7792d942-0539-11e5-8e7f-7e52ff1d8b86.JPG)
![7](https://cloud.githubusercontent.com/assets/11805589/7857509/7c27ebfa-0539-11e5-8157-9b1d085be67a.JPG)

**Comment by ihteandr** [comment]
зделал без филтра так тоже нармально
